### ISSUE TITLE
근무 정정 신청 풀모달 개발

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project2-team4-dayus#107]
## 📃 Describe

근무 정정 신청을 위한 풀 모달을 개발하고,
api를 구현한다.

## ✅ Tasks

- [x] 정정 신청을 위한 풀 모달 컴포넌트 마크업
- [x] useRef를 사용하여 사용자의 입력값에 따라 데이터를 변경하도록 기능 작성
- [x] 커스텀 훅을 사용해 각각의 데이터 변화를 포착
- [x] api 통신이 진행중일 때, 사용자의 동작을 막고 완료 되었을 때의 조건 처리를 진행한다.

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
