### ISSUE TITLE
[FEAT] 메인 캘린더 하단에 카페 행사 정보를 조회합니다. 

### ISSUE THREAD

**Issue by bbjbc** [Dev-FE-2/toy-project2-team4-dayus#123]
## 📃 Describe

메인 캘린더 하단에 카페 행사 정보를 조회합니다. 

## ✅ Tasks

- [x] 카페 행사 정보를 firestore에 등록해요.
- [x] 카페 행사 정보 조회하는 api를 제작해요.
- [x] 카페 행사 정보 컴포넌트를 제작해요.

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
