### ISSUE TITLE
[FEAT] 하단에서 올라오는 모달 컴포넌트를 퍼블리싱합니다. 

### ISSUE THREAD

**Issue by bbjbc** [Dev-FE-2/toy-project2-team4-dayus#16]
## 📃 Describe

하단에서 올라오는 모달 컴포넌트를 제작합니다. (bottom sheet) 

## ✅ Tasks

- [x] 아래에서 위로 올라오는 애니메이션을 구현해요.
- [x] 드래그로 모달을 내릴 수 있도록 해요.
- [x] 오버레이 클릭 시 닫혀야 해요.
- [x] 모달이 열려있을 때 배경 스크롤 방지해요.
- [x] `React Portal`을 사용하여 모달을 body에 직접 마운트해요.

## 📋 Ref

![image](https://github.com/user-attachments/assets/08686f57-b3e7-42fb-b432-ddfc5e5fd74d)
