### ISSUE TITLE
[FEAT] 탭 UI 컴포넌트 개발

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project2-team4-dayus#20]
## 📃 Describe

탭 UI 컴포넌트 개발

## ✅ Tasks

- [x] styled-component 형태로 UI 마크업
- [x] 탭 활성화 관련 개발
- [x] 컴포넌트 확장성 대비

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
