### ISSUE TITLE
ERD 추가 및 docs 폴더 추가

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project2-team4-dayus#38]
## 📃 Describe

erd 생성에 의한 docs 폴더 추가

## ✅ Tasks

- [x] docs 폴더 추가
- [x] erd 파일 이미지 추가
- [x] 사용 참고사항 md 파일 추가

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
