### ISSUE TITLE
[FEAT] 급여 페이지의 지난달 급여 정보 아코디언 개발

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project2-team4-dayus#50]
## 📃 Describe

지난달 급여 정보 아코디언 개발

## ✅ Tasks

- [x] 아코디언 UI 마크업
- [x] 아코디언 여닫힘 핸들러 추가
- [x] 사이드 이펙트를 통해 받아올 데이터 정제

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
