### ISSUE TITLE
[FEAT] 급여 목록 무한스크롤 기능 개발 

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project2-team4-dayus#53]
## 📃 Describe

급여 목록 페이지의 지난 급여 목록 무한 스크롤 개발

## ✅ Tasks

- [x] 무한스크롤 기능 컴포넌트 개발
- [x] 급여 목록 출력을 위한 리스트 컴포넌트 마크업
- [ ] MSW 활용하여 목 API 개발 및 테스트

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
