### ISSUE TITLE
[FEAT] 이벤트 삭제 관련 로직을 추가합니다. 

### ISSUE THREAD

**Issue by bbjbc** [Dev-FE-2/toy-project2-team4-dayus#70]
## 📃 Describe

캘린더에 이벤트 삭제 관련한 로직을 추가해요.

## ✅ Tasks

- [x] 휴지통 아이콘 누르면 아래 버튼 생기도록 해요.
- [x] 현재 `color.id` 값으로 삭제하는데 type을 추가해 변경해요.
- [x] 리스트에서만 사라질 뿐 아니라 캘린더 라벨링도 사라지게 해요.

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
