### ISSUE TITLE
[FEAT]급여 목록 페이지 컴포넌트와 mock api 테스트 연동

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project2-team4-dayus#72]
## 📃 Describe

사이드 이펙트가 발생할 컴포넌트에 mock api를 연동한다.

## ✅ Tasks

- [x] 급여 정보 조회 API 개발
- [ ] component - mock api 연결
- [ ] 사이드 이펙트에 의한 조건 처리 및 컴포넌트 상태 관리

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
