### ISSUE TITLE
[REFACTOR] 급여 데이터 관련 데이터 기술 부채 청산 

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project2-team4-dayus#76]
## 📃 Describe

설계 및 사전 작업을 진행하면서 발생한 기술 부채 청산을 위한 리팩토링

## ✅ Tasks

- [x] 데이터 타입 모델링 설계 및 수정
- [x] 불필요한 데이터 하드코딩 삭제 및 수정
- [x] utlity 함수 적용

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
