### ISSUE TITLE
[FEAT] 급여 목록 페이지 API 및 컴포넌트 취합

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project2-team4-dayus#90]
## 📃 Describe

급여 목록 페이지의 API 및 컴포넌트를 취합하여 페이지에서 api 및 파라미터 관리를 시행한다.

## ✅ Tasks

- [x] 급여 목록 페이지 api 연결
- [x] 컴포넌트 데이터 렌더링
- [x] 사이드 이펙트 에러 처리

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
