### ISSUE TITLE
근무 정정 정보 조회 페이지 개발

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project2-team4-dayus#98]
## 📃 Describe

근무 정정 정보를 조회하기 위한 페이지를 개발합니다.

## ✅ Tasks

- [x] 근무 정정과 관련한 type 선언
- [x] 페이지 컨텐츠 마크업 및 순수 기능 함수 추가
- [x] 근무 정정 정보 조회 api 및 목업 데이터 생성
- [x] 근무 정정 페이지 api 연결 및 조건 제어

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
